### ISSUE TITLE
Documentation example doesn't create an animation

### ISSUE THREAD

**Issue by mantielero** [sciapp/gr#112] opened 2020-04-23 18:00 UTC
When I run [this example](https://gr-framework.org/examples/anim.html), the GR part seems to close and create a new window per frame. This way it is very slow and there is no animation at all.

**Comment by FlorianRhiem** [comment] 2020-04-24 08:43
Could you try to reproduce the issue with this reduced snippet?

```python
from numpy import arange, sin, pi
from time import time, sleep
import os
os.environ["GKS_WSTYPE"] = "gksqt"

from gr.pygr import plot

x = arange(0, 2 * pi, 0.01)
for i in arange(1, 200):
    plot(x, sin(x + i / 10.0))
    sleep(0.0001)
```

**Comment by mantielero** [comment] 2020-04-24 11:01
This snippet works fine

**Comment by FlorianRhiem** [comment] 2020-04-24 11:11
Thank you for testing that. That's odd, there seems to be some interaction between pylab and GR then? I have updated the example to switch the order and use matplotlib.pyplot directly. Could you please try whether you still have the issue of gksqt opening and closing?

```python
from numpy import arange, sin, pi
from time import time, sleep
import os

os.environ["GKS_WSTYPE"] = "gksqt"

num_frames = 200

x = arange(0, 2 * pi, 0.01)

# create an animation using GR

from gr.pygr import plot

tstart = time()
for i in range(num_frames):
    plot(x, sin(x + i / 10.0))
    sleep(0.0001)

fps_gr = int(num_frames / (time() - tstart))
print('fps  (GR): %4d' % fps_gr)

# create the same animation using matplotlib

from matplotlib.pyplot import plot, draw, pause

tstart = time()
line, = plot(x, sin(x))
for i in range(num_frames):
    line.set_ydata(sin(x + i / 10.0))
    draw()
    pause(0.0001)

fps_mpl = int(num_frames / (time() - tstart))
print('fps (mpl): %4d' % fps_mpl)

print('  speedup: %6.1f' % (float(fps_gr) / fps_mpl))
```

**Comment by mantielero** [comment] 2020-04-24 12:15
Now it works fine:
```
$ python bench.py 
fps  (GR):  437
fps (mpl):   44
  speedup:    9.9

```

**Comment by FlorianRhiem** [comment] 2020-04-24 12:17
I'm not sure what might be causing this interaction between the two libraries, but I'll update the example in the python-gr repo. Thank you for your help!

**Closed as completed by FlorianRhiem** 2020-04-24 12:17 UTC
