### ISSUE TITLE
`mathtex2` output looks a bit deformed

### ISSUE THREAD

**Issue by asinghvi17** [sciapp/gr#105] opened 2020-03-31 11:40 UTC
In Julia, executing the following code:
```julia
using GR # v0.48
GR.settextfontprec(231, 3)
GR.mathtex(0.1, 0.1, raw"x_{f}=\int_{t_{*}}^{\infty} d t \frac{k}{a^{2}(t)}\sqrt{1+\frac{k^{2}}{a^{2}(t)}}")
```
yields the image:
<img width="278" alt="Screen Shot 2020-03-31 at 5 08 35  47800PM" src="https://user-images.githubusercontent.com/32143268/78022250-476ccc80-7372-11ea-98d1-bf99d9fc4eb6.png">

Is there a way to make the integral sign larger, and to ensure that the square root's top line maintains its size?

**Comment by FlorianRhiem** [comment] 2020-03-31 12:23
Hey, thank you for the bug report. The mathtex parser and the outline font precision are both rather new, so there are still a few adjustments that need to be made for the two to fit together. 

I've updated some spacing parameters for the sqrt horizontal rule and get the following result:
<img width="255" alt="image" src="https://user-images.githubusercontent.com/4411847/78024040-ff40b080-7357-11ea-83d2-8d1a7844677a.png">

I've also made a slight change to allow `\int` and `\sum` as auto-sizable left delimiters. This allows a formula like this: `x_{f}=\left\int_{t_{*}}^{\infty} d t \right. \frac{k}{a^{2}(t)}\sqrt{1+\frac{k^{2}}{a^{2}(t)}}` which is then rendered as:
<img width="283" alt="image" src="https://user-images.githubusercontent.com/4411847/78025523-79723480-735a-11ea-9fa2-fecf3cb81504.png">
Would this be alright for you? Using `\int` without `\left` will still yield the regular integration symbol with limits below and above it.

**Comment by asinghvi17** [comment] 2020-03-31 12:42
That looks a lot better; would it be at all possible to have the integration limits in the "correct" places?  Another option could be directly right of top for the superscript, and right of bottom for the subscript.

I've also noticed that the `\sqrt` seems a little thick, and there seems to be a constant right shift at the beginning of each delimiter.

Thanks a lot for the help!

**Comment by FlorianRhiem** [comment] 2020-03-31 13:00
Not at this time, though that might be something to look at in the future.

Symbols like `\sqrt` and `\left(` are rendered using their regular characters, scaled up to match the required height. This results in characters which are equally wider and thick. I suspect their width is also the cause for the right shift you are noticing.

In your example, a way to decrease the required height is to use `\dfrac` like this `x_{f}=\int_{t_{*}}^{\infty} d t \dfrac{k}{a^{2}(t)}\sqrt{1+\dfrac{k^{2}}{a^{2}(t)}}`:

<img width="213" alt="image" src="https://user-images.githubusercontent.com/4411847/78029065-45017700-7360-11ea-902e-4e1eaf15cbdf.png">

**Comment by FlorianRhiem** [comment] 2020-04-01 06:02
The changes have been [merged into `develop`](https://github.com/sciapp/gr/commit/3c118708586b50fecab3ef90209560037dd6e877) and will be part of the next minor release.

**Closed as completed by FlorianRhiem** 2020-04-01 06:02 UTC
